### ISSUE TITLE
Popup ID getting echoed onto pages after update

### ISSUE THREAD

**Issue by ztackett11** [PopupMaker/Popup-Maker#1077]
## Describe the bug

Above the footer of the websites we use this plugin on the ID values of the popups is getting output on to the screen

They are being echoed out before the containers that are hidden at the bottom of the page source.

10822 10829 10832 3140 3138 2928 2582 2488 2482

The issue seems to be coming from this ternary operation in popup.php

$labelledby = pum_get_popup_title() !== '' ? 'aria-labelledby="pum_popup_title_' . pum_popup_ID() . '"' : '';

Removing the ternary operation and then changing the first HTML div aria-labeledby attribute to this

`aria-labelledby="<?php echo esc_attr( pum_get_popup_title() !== '' ? "pum_popup_title_' . pum_popup_ID() . " : '' ); ?>"`

Seems to fix the issue

## Site information
Popup Maker version: 1.20.0

WordPress version: 6.6.2

PHP version: 8.1.29

## Expected behavior
The plugin should not be echoing out anything directly onto the page

## Current behavior
After the most recent update, PopUp Maker is echoing out the value pum_popup_ID() onto all pages.

## Steps to reproduce
1. Update plugin to newest version
2. Go to any page
3. All popup ID's for every currently created popup will be displayed above the footer in one long text string

## Errors
N/A

## Additional context
The issue is stemming from the update to the popup.php file

Specifically the addition of the ternary operation on line 9, 

if instead of trying to use the ternary extra 

I believe the issue is because instead of returning the value from the pum_popup_ID() function, it is echoing the value out and with the function being called within the ternary operation, the value is being output explicitly

**Comment by marklchaves** [comment]
Hey @ztackett11 , good catch.

But, I think `esc_attr()` is mangling the `aria-labelledby`.  So pushing the ternary into the first div only moves the bug into the div.

If I remove the call `esc_attr( $labelledby )`, the `aria-labelledby` in the rendered div looks correct. E.g., `aria-labelledby="Forms Test"`.

Not saying removing `esc_attr()` is the fix. Just saying the combo of calling that with the title string looks like the culprit.

**Comment by danieliser** [comment]
The issue was much simpler than that ,and only impacted popups with titles set.

In v1.20.0 we started enforcing more strict PHPCS rules, we also cleaned up those templates to not have ternary statements within html tag enclosures directly (IE no true ? '' : 'attr=""' within <div ...>).

Previously, we rendered the popup ID directly into the attribute via the ternary inside a `<div>`.

The issue itself stems from using a template function (one that echos) inside the newer variable declaration, which should have been a getter only returning the popup ID as a string.

`v1.20.1` has been released to resolve this. Please update and confirm yourselves.

Thanks for the report.
