### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by mungle** [PopupMaker/Popup-Maker#124]
Hello, I'm trying to add custom css box from "[Custom CSS by techsperia] (https://wordpress.org/plugins/custom-css-by-techsperia/)" plugin. To achieve it I edited techsperia-css.php adding this line:

    add_meta_box('custom_css', 'Custom CSS', 'ts_custom_css_input', 'popup-maker', 'normal', 'high');

But it doesn't work...
Any suggestions, please?

**Comment by danieliser** [comment]
'popup-maker' should be 'popup' but likely that will add the box but not add any CSS to the pages with the popup. This is because the popup isn't loaded like a page. They are appended to a page. Likely that plugin renders custom CSS for each page not things appended to them. If it did then a recent post widget for instance would add extra CSS for every post in the widget.

You can add your own CSS based on the popup id or theme id.

Each popup has a unique CSS id of popmake-# where # is the post id. They also get the class theme-# where # is the id of the popup theme.

Using those you can add extra CSS to #popmake-123 or .theme-456 depending if you want to target one popup or all popups with a specific theme.

**Comment by danieliser** [comment]
It may work but we don't use the_content for the popups so you may have to add a custom filter replicating what they do with the_content for our loop of the_popup_content and instead of using get_the_ID you would use get_the_popup_ID.

**Comment by mungle** [comment]
:thumbsup:
