### ISSUE TITLE
1.3 serves wrong theme for non-logged in users

### ISSUE THREAD

**Issue by dsent** [PopupMaker/Popup-Maker#129]
The users that are not logged in are served the default theme. And by “default” I mean really some default values I did not set for my theme.

Logged in users (all admins) get this stylesheet:
```
<style id="popup-maker-themes"  type="text/css">/* Popup Theme 989: Default Theme */
    .popmake-overlay.theme-989, .popmake-overlay.theme-default-theme { background-color: rgba( 0, 0, 0, 0.25 ) } 
    …
</style>
```

While all non-logged in users get some default values that I suspect are hardcoded into the plugin (because I haven't set anything like this anywhere):
```
<style id="popup-maker-themes"  type="text/css">/* Popup Theme 989: Default Theme */
    .popmake-overlay.theme-989, .popmake-overlay.theme-default-theme { background-color: rgba( 255, 255, 255, 1 ) } 
    …
</style>
```

Had to roll back to 1.2 which have issues by itself, but manageable ones.

**Comment by danieliser** [comment]
@dsent - That doesn't make any sense. To clarify your issue description makes sense, but not the issue itself. Let me explain.

First the new method of styling the popups is pure CSS, where before it was a JSON object of settings passed to JS to theme the popup on the fly, left it hard for users to customize the popups using their own CSS without using !important.

Also that meant that if you had 20 themes we had to load all 20 on every page load and process them adding more load time.

Now CSS is processed when a transient is missing. The transient has an expiration of 7 days and is automatically deleted when a theme is updated.

Second we don't have any default/hardcoded values for the CSS generation they are taken from existing theme data.

So to explain further why this issue makes no since. The transient value should generate the same CSS everytime for 7 days reguardless of who is logged in. The only thing here that comes to mind is if your server, like mine, is cache heavy. When I am logged in the page refreshes every time with updated content/html. When not logged in I get a cached copy that can be hours/days old. I think this is made most evident by the fact that both logged in & logged out CSS use the same Theme ID(989). That is a single post type ID so settings should be the same each time since the same function is called to generate them.

Let me know if that makes sense or if you can test clearing your cache etc.

**Comment by dsent** [comment]
Well, my first guess was some problem with the cache (I use WP Super Cache).
But there are two more things:
1) Clearing the cache does not help
2) Why would the cache contain the wrong CSS in the first place if I've never set values like these? I have only one theme and it was the same before the update.

I'll set up a mirror of my site to experiment more extensively.

**Comment by danieliser** [comment]
@dsent - The default theme installed when you first install Popup Maker uses a white overlay color. That would be the value of 255,255,255 1.

Since the themes are rendered in the head using a <style> tag they are cached there. So essentially if you installed, loaded any front end page, then edited the default theme to the current values and never cleared the page cache.

Beyond that I have no clue. As I said the CSS is cached in a transient, though super cache may be overriding the WP Transient system but I don't think that should have much to do with it.

You may be best off to create a new popup theme and delete that older one. Assign the new one to your popups.

**Comment by dsent** [comment]
That's embarrasing, but I've updated the plugin again, cleared the cache and it just worked.
Let's suppose that was magic. Sorry for the false alarm.
I guess I should add “Try again the next day” rule somewhere near “Try turning it off and on again” to my list of things to try before contacting the devs :-)

**Comment by danieliser** [comment]
@dsent - I do know that with my hosting of WP Engine even when I clear cache & cdn, it can take quite a while before it actually clears and refreshes in my browser. Not sure why that is but just something to be aware of.

Thanks for reporting back.

Please take a moment to <a href="https://wordpress.org/support/view/plugin-reviews/popup-maker">rate and review the plugin</a> and or support.
