### ISSUE TITLE
Bug in Add/Edit Theme tool?

### ISSUE THREAD

**Issue by dgouldmba1996** [PopupMaker/Popup-Maker#133]
HI,  Please see the attached video.  Any ideas?

http://screenpresso.com/=0Stae

**Comment by danieliser** [comment]
@dgouldmba1996 Definitely a bug, but not sure its caused by popup maker. Those boxes and styles that are messed up are built into WP. We create them using WP functions for the most part.

Looks like some other plugin has possibly added CSS that is conflicting with those panels. This is the first I have seen that so likely something that is not used by a whole lot of sites. That eliminates things like EssGrid etc.

You can paste your debug log here if you like and we can go from there. Popup Maker -> Tools

**Comment by dgouldmba1996** [comment]
Hi Daniel,

 

Im not a developer…but solid with computers.  Where can  I find/create a debug log?  I looked at Popupmaker>tools and just saw a sys info tab and an import export tab.

**Comment by danieliser** [comment]
@dgouldmba1996 - The system info tab is what we are after, shows a list of active plugins and theme info so we can try to narrow down the cause.

**Comment by dgouldmba1996** [comment]
Thanks Daniel.  Here you go

 

D
