### ISSUE TITLE
Fixed position option is ignored (1.3.7 to 1.3.9 regression?)

### ISSUE THREAD

**Issue by dsent** [PopupMaker/Popup-Maker#179]
Updated the plugin from 1.3.7 to 1.3.9 and my popups stopped being fixed on screen (started scrolling with the page). “Checking this sets the positioning of the popup to fixed” option is checked, but ignored.
I can't really uncheck it too: if I do that and update, it is still checked.

Had to restore from backup and found out that in version 1.3.7 the option I mentioned was **unchecked** on all popups. And I can't update its value too (it stay unchecked even if I check it and click update). But the popups' position is fixed on the screen anyway...

**Comment by danieliser** [comment]
@dsent - The option is working correctly. All of these issues stem from the original problem that fixed position is both unreliable and not very mobile friendly for responsive popups. Thus when using responsive sizes its best to not use fixed. In the case that you do we use CSS to disable fixed when the popup has a responsive size & the screen is below a threshhold. This is actually the desired behavior of most of the users we talked to.

Essentially fixed works fine on large screens as you would expect. On small screens that the popup would likely be too tall for and most of the popup would be off screen with fixed position, so that had to be resolved.

Hope that helps.

If you like you can override our CSS on a per popup basis or globally in your own stylesheet. Here is the rule in question.

https://github.com/PopupMaker/Popup-Maker/blob/master/assets/css/site.css#L117

https://github.com/PopupMaker/Popup-Maker/blob/master/assets/css/site.css#L123

**Comment by danieliser** [comment]
We may adjust the point at which it is disabled or give the editor an option to override it. That isn't out of the question, but we couldn't leave it enabled globally as it was generating 4-6 support requests a week.
