### ISSUE TITLE
Conditional Triggers not functional in Chrome v.50

### ISSUE THREAD

**Issue by raihje** [PopupMaker/Popup-Maker#315]
Currently in Chrome the pop-up must either trigger on all pages, or no pages.
However viewing in MS Edge and Firefox the pop-up works as expected.

**Comment by danieliser** [comment]
Unfortunately that is not possible. Conditions are applied before the code is sent to the browser using PHP. Because of this there is no way for Chrome to be a factor.

Also will point out that I use Chrome for 100% of the development work so it definitely does work by default.

No onto possible issues.

Likely caching. If your site uses page caching etc and your logged in caching is ignored. So if your cache is out of date then the popup could seemingly work in browsers that you are logged in to. 

Or vice versa if the problem wasn't there before and now is then logged in browsers wouldn't show old cached copy.

The only other possibility is that something on your site is throwing a JS error but only on chrome.

Do you have a link?

**Comment by raihje** [comment]
http://856ltd.com/brauner/
In Edge on my local machine the pop-up appears on the properties page.
In an incognito chrome the pop-up doesn't not appear unless I set triggers to all pages.
Conditions are: Pages Selected: Properties AND Search Pages.

**Comment by danieliser** [comment]
@raihje - With those conditions, it won't show anywhere :).

Check out our guide on conditions: http://docs.wppopupmaker.com/article/140-conditions

No page is going to be both Properties & Search Page at the same time.

Conditions are applied to the page, not the popup. IE I want this popup to appear on a page that is _____ (AND/OR) ______

Try doing them as an OR condition instead.

**Comment by danieliser** [comment]
Oh forgot to mention, if its working in one and not the other, there are only 2 possibilities, site/browser caching or a JS error in one browser only.

**Comment by raihje** [comment]
Alright I'll change the conditions and get back to you asap. Thanks for the quick response.
