### ISSUE TITLE
How to add maximize and minimize buttons on the popup window

### ISSUE THREAD

**Issue by Terragal** [PopupMaker/Popup-Maker#371]
Can you tell me how to do the maximize and minimize button on the pop up window (the modal), or can you please make an update to the popup maker that will do that?!

Thank you

**Comment by danieliser** [comment]
@Terragal - I'm not sure that would be a viable feature for the core plugin. But can you elaborate to be sure. Do you mean like the minimize/maximize buttons for apps & the browser itself? What purpose would that serve to the general user with a marketing popup or contact form?

More info may clarify better.

**Comment by Terragal** [comment]
So I find that popup maker integrate very good with one of my plugin that is a chat plugin. The all properties of popup maker are very good. Now. I have the shortcode of my chat in the popup it is trigger by click and open, but I want that my users to have the choice to minimize the popup window down right, or to maximize the popup. So next to close button I like a button for minimize and maximize. Or by click in the border or outside the popup window, the popup will close down like let say facebook chat. Can you guide me how to do that. Thank you.

**Comment by danieliser** [comment]
@Terragal Ok now that I know what your after I don't think you need any modifications made.

Check out this guide: https://wppopupmaker.com/guides/slide-out-menu/, specifically page 3 https://wppopupmaker.com/guides/slide-out-menu/3/. That guide uses a sticky button like your after so you can copy the code for that.

You simply need a sticky button fixed to the edge of the screen, then to set your close button text to "-" rather than "x"

Whether you close or "minimize" the popup the effect is the same. IE closing = hiding, minimizing = hiding.

So just re-purpose close to suite your needs for minimizing.

If you want to get real fancy you can use the pumAfterOpen JS event to hide the fixed button, and pumAfterClose to show it again.

In any case what your after can be accomplished with no modifications to the plugin itself.

Hope that helps.

**Comment by Terragal** [comment]
Thank you Danieliser!

**Comment by danieliser** [comment]
Closing this since its not something we will be doing to the core plugin.
