### ISSUE TITLE
Give Click Trigger the ability to also close a popup

### ISSUE THREAD

**Issue by waltermesser** [PopupMaker/Popup-Maker#396]
So if I had a Tool Tip Popup, for example, the Click Trigger would both open and close the popup - just like the HelpScout Beacon on the site.

**Comment by fpcorso** [comment]
@danieliser What are your thoughts on how to implement this? Should we do it automatically? Or, add a new setting in the click trigger modal? If a new setting, should it default to working this way or should it need to be turned on?

**Comment by danieliser** [comment]
@fpcorso I wonder if this should be an extension. Similar to the custom code we use to create a floating button.

As for where it goes that could probably be a new trigger type. In this way it follows the targeting of the popup its used on.
1. New trigger type: Fixed Button or similar.
2. Trigger options might include: 
- Should offer delay like time delay.
- What should be shown: Button or Popup
- Should button dissappear when popup open.
- Should button stay when popup closes.

Alternatively it could be added to a new tab/subtab as settings that just work with any trigger, but same settings likely.

3. There should be new settings in the popup theme editor to support styling the floating button.

**Comment by fpcorso** [comment]
@danieliser I think we are interpreting this one slightly different from each other.

My interpretation was that this would extend the click trigger to cause both opening and closing. So, if someone would click on a link or image within the page to open a popup, clicking on that same element would also close the popup.


However, it seems you are interpreting it as building a whole new feature for a floating button. Do you think that fits within the scope of Popup Maker? If enough people would use that, I could see how that might fit in but not sure if that should be within core or as an extension.

**Comment by danieliser** [comment]
@fpcorso I knew what he meant when he posted it. This is pretty close to the time when he published the guide & example that has a fixed/floating menu button: https://examples.wppopupmaker.com/playground/slide-out-menu/

And yes I think its a viable premium feature, gets requested regularly, and others have it: https://www.icegram.com/tabs/

**Comment by danieliser** [comment]
@fpcorso Maybe I'm missing something., looking from your interpretation, what purpose does it serve, or use case does it solve unless used like the examples above? I can't see how it would be used, unless they were trying to make click based tooltips, in which case probably not the best option to use PM as we previously discussed.

**Comment by fpcorso** [comment]
@danieliser I wasn't necessarily advocating for usage at this point. More of just trying to understand what this issue would entail.

That said, I do agree that your interpretation would better align with Popup Maker's scope and our plans.

However, I think how this issue is currently written implies my interpretation. So, I think we should either:

1. Completely re-write this issue to be more like your interpretation.
2. Create a new issue with your idea and leave this one to preserve our choice of not pursuing this original idea at this time. <--- This one is what I would suggest we do.

Either way, I think we should look more into the solution you discussed so, whichever choice we make for the issue, I think we should slate that solution for 1.12 tentatively so we can discuss it more thoroughly in the near future.

**Comment by danieliser** [comment]
@fpcorso Number 2 sounds right. I don't see a need for this functionality as written currently.
