### ISSUE TITLE
New plugin dashboard.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#404]
Similar to the newest concept in ninja forms. Moving the extensions front and center.

I like  the way EDD did it in the latest build with the All Downloads page having some parent tabs

"Downloads" | "Apps & Integrations" | "Add New"

**Comment by NoahjChampion** [comment]
@danieliser are you asking for feedback on this or just stating a roadmap feature?

**Comment by danieliser** [comment]
@noahjchampion Both.

**Comment by danieliser** [comment]
@FearlessMode Sorry just realized I tagged the wrong person. Both, do you have any feedback? Nows the time as this is slated for v1.8 and 1.7 is going into beta shortly.

**Comment by FearlessMode** [comment]
Hi @danieliser 

You tagged the right person. I had a username change since (and will probably under one more in the soon future) and forgot to check this out. 

I've never used EDD believe it or not 💯 . It's probably the only major/popular plugin that I haven't. Sites have always had the need for Woo for me. 

However, I just installed to check it out and provide some feedback. 

I like this idea and think it's smart. I think it's a rather brilliant and yet still subtle and a UX improvement. It also offers the option of cutting down on the menu items on the left (if you choose to remove that), while bringing the extensions front and center making sure users know about them (for obvious reasons).

For me, if I were doing it I would provide a filter or admin option so devs can choose to hide the extensions tab in case they chose to hide it from the admin menu already as to personally offer such extensions to their clients via themselves and not your website itself; or for those who have white labelled the admin from such options for their clients but are allowing access to create popups and or edit them.

**Comment by danieliser** [comment]
@FearlessMode Thanks for the feedback.
