### ISSUE TITLE
Contact Fotm 7 popup email tags

### ISSUE THREAD

**Issue by parfilov** [PopupMaker/Popup-Maker#441]
Hello! That's would be nice if you'll make two additional mail tags for CF7. For example:
[popup-name] and [popup-title]
With this tags we could send addition data about form submitions.

And the second part of the question. There is a plugin at WP directory, name Contact Form 7 Modules. It has tag:
"custom_field-[Name] – The value of a post or page’s custom field. If you had a custom field “Foo”, you would use the following as the hidden field value: custom_field-Foo"

Maybe I can use value of the popup title custom field to solve my case? And so what value the popup title custom field has?

Thanks for the answer!

**Comment by danieliser** [comment]
@parfilov - Won't work to use the other plugin. We use custom loops so that you can still detect the current page, so when they call get_post_meta inside a popups content it returns for page not the popup. We do this for the reason you described, tracking the page a popup was shown on.

In your case since you can't insert a form on the page more than once using CF7 reliably, each form should already be paired with a specific popup and use targeting conditions to limit where that form/popup is shown.

Likely we won't be adding any more form integrations as we are aiming to add more generic form support in the upcoming version to make any form work with PM. This means removing direct integrations as they wouldn't be required. So adding more code to that isn't gonna happen.

If I misunderstood your use case apologies, but I can't see this being very useful for bulk of our users which means we likely can't consider it as a future feature.

**Comment by parfilov** [comment]
@danieliser Thanks for the answer. It will help me to seek another solution.
