### ISSUE TITLE
PopupMaker plugin works great but breaks pages that already use Contact Form 7 shortcodes 

### ISSUE THREAD

**Issue by mjwyatt** [PopupMaker/Popup-Maker#444]
Has anyone else come across this bug? Had to disable the plugin from my live site at blujazzakron.com. Popup worked great on home page as intended, but when I navigated to either of my pages that used the Contact Form 7 shortcode on them, it rendered the pages blank. 

Any ideas?

**Comment by danieliser** [comment]
@mjwyatt No ideas unless you are using the same CF7 shortcode on the page and in the popup. Most form plugins only support rendering each form once per page or you can see rendering or submission/confirmation issues as their JS doesn't know how to handle multiple instances.

Other than that, your best bet is disabling all popups and then enabling one at a time as it is most likely something in a popup, rather than the popup itself. IE we get the blame when content inserted into popups causes trouble because when you disable PM that content no longer gets rendered and it magically starts working correctly.
