### ISSUE TITLE
PUM v1.7 beta1: Reorder popup cookie menu options

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#467]
In version 1.7, encourage plugin users to select the 'On Popup Close' cookie option by moving it to the top of the cookie menu option list. 

Within the Popup Admin at:

'Popup Settings (box)' >> 
'Triggers' >> 
'Add New Cookie (button)' >> 
'When Should Your Cookie Be Created (dialogue box)', 

change the menu order FROM: 

On Popup Open
On Popup Close
Subscription Form: Successful
Subscription Form: Already Subscribed
Manual JavaScript

TO:

On Popup Close
On Popup Open
Subscription Form: Successful
Subscription Form: Already Subscribed
Manual JavaScript

**Comment by danieliser** [comment]
Any particular reason that should be the default?

**Comment by rgadon107** [comment]
@danieliser As plugin users scan the drop-down menu, they tend to focus on the first item presented in the list. In my opinion, users unfamiliar with PUM, or the relative value of the choices presented to them will likely choice the first option to presented to them. That option is 'On Popup Open'. 

Typically, we encourage plugin users to set the cookie to ’On Popup _Close_‘. If we want to encourage that selection among our users _as the default_ , then _nudge_ them by changing the list order to start with _‘On Popup Close’_.

**Comment by danieliser** [comment]
I’m more curious why we would be recommending a specific cookie event? Each has its own purpose. If it’s an announcement that should only be seen once then on open is correct in most cases.Not saying we can’t just trying to make sure it’s justified.---- On Wed, 10 Jan 2018 16:33:50 -0500  Robert Gadon<notifications@github.com> wrote ----@danieliser As plugin users scan the drop-down menu, they tend to focus on the first item presented in the list. In my opinion, users unfamiliar with PUM, or the relative value of the choices presented to them will likely choice the first option to presented to them. That option is 'On Popup Open'. Typically, we encourage plugin users to set the cookie to ’On Popup Close‘. If we want to encourage that selection among our users as the default , then nudge them by changing the list order to start with ‘On Popup Close’.  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rgadon107** [comment]
We don't educate out plugin users effectively within the plugin UI  on why one cookie type if preferable over another ('On Popup Open' v. 'On Popup Close'). A user would have to dig into the documentation to figure that out. (Some do; many do not). 

New plugin users are uninformed about which to cookie to use. They typically choose 'On Popup Close' (if they set up a cookie at all). That selection typically suits their needs, as the cookie gets set if a visitor chooses the 'Close' button. 

Although as I think about it now, if a cookie gets set 'On Popup Open', then setting the cookie is entirely independent of site visitor behavior. The cookie will get set whether a visitor closes the popup or not. 

Hadn't thought of that until just now.
