### ISSUE TITLE
Building Popups in Reusable Manner

### ISSUE THREAD

**Issue by rgadon107** [PopupMaker/Popup-Maker#473]
@danieliser I've encountered a PUM user who is generating 60+ popups on their site. We both know that such a strategy doesn't scale well, and there are better ways to manage this. I haven' looked closely at the content that they want to render on their site. 

Let's assume that much of the content is boilerplate, and only a small part of each popup varies. Or perhaps the content varies greatly between popups, and it structured the same on each popup. 

Rather than passing in much of the same content between popups, or passing in the same structured, hard-coded content, have you given any consideration to allowing PI users to make their plugin content reusable?  It would probably mean giving users the ability to build custom metaboxes for each popup, and then building multiple popups from the data by a looping process.

**Comment by kelleg1** [comment]
I had a somewhat related suggestion regarding adding site-wide default options for popup triggers in issue #474.

**Comment by danieliser** [comment]
Globals presets would be one thing, not sure exactly what you are proposing with "allowing PI users to make their plugin content reusable? It would probably mean giving users the ability to build custom metaboxes for each popup, and then building multiple popups from the data by a looping process"

That sounds like an extremely complex process both for development/processing, but more importantly for users to learn on top of so many other complex settings (conditions, triggers + cookies). Our goal for the last few versions has been to simplify and remove unintuitive functionalties that lead to increased learning curve.

Just some stats for you to ponder when considering adding major new complexities:

Last month we had roughly 28,500 activations in freemius last month (new installs + users upgrading from older versions prior to v1.4). Of those we had ~6200 deactivate/delete the plugin. IE 1/4 of users are immediately unable to get what they want and simply find another solution. That is way to high and until we address that something like described above would be too much.

That said nearly anything you can imagine could already be done for any one site developer that would be interested in the functionality your describing anyways. You can create custom popup templates, render popups via manual PUM_Popup objects (rather than the editor) if needed as well as filter or hook nearly anything to modify it on the fly.

Add a simple metabox as a developer to popups to choose which filters to enable/disable for each popup and you can get close to what your after.

If you want to outline it in more detail assuming I didn't get the idea properly I will take another look.

**Comment by rgadon107** [comment]
@danieliser Thank your for the feedback and perspective.
