### ISSUE TITLE
data-* attributes missing

### ISSUE THREAD

**Issue by rolka** [PopupMaker/Popup-Maker#550]
There are no data-attributes on my production website, but data attributes are present on local website.

So, this is a rendered element which triggers popup on local website:

`<p id=”el-d-for-propower” class=”manual-download-link pum-trigger” data-popup=”1661″ data-settings=”[object Object]” style=”cursor: pointer;”>ProPower</p>`

And same element rendered on live website:

`<p id=”el-d-for-propower” class=”manual-download-link pum-trigger” style=”cursor: pointer;”>ProPower</p>`

As you can see- data-popup and data-settings are missing.

Has data-* attrbutes been removed in latest version?

I do manual Google Captcha rendering on each form in each popup, so I need data-popup values.

**Comment by danieliser** [comment]
@rolka Sorry you didn't get a response. Never saw this one honestly, but it was before Github Notifications.

We have moved away from that slowly, primarily because its messy and unneccessary when we can put it all into the `pum_vars.popup` global JS variable and pull it from there without limitations or leaking into HTML markup.
