### ISSUE TITLE
Does not work with Calculated Fields Form plugin

### ISSUE THREAD

**Issue by au85** [PopupMaker/Popup-Maker#57]

**Comment by danieliser** [comment]
@au85 - Can you elaborate as to how it doesn't work or what breaks?

**Comment by au85** [comment]
The popup only shows the shortcode, not the actual form.

**Comment by danieliser** [comment]
Hmm, Will have to take a look at their code, sounds like they are doing something out of the ordinary as shortcodes definitely work and any shortcode should process when we call do_shortcode on the content. Thanks for the report.

**Comment by au85** [comment]
Well, it works today live, but when creating the popup the preview only shows the shortcode. Also, the live popup does not allow scrolling.

**Comment by danieliser** [comment]
@au85 - Unfortunately the live preview can't work for all shortcodes, this is due to the fact that some plugins only register their shortcodes for the front end of the site meaning they won't work for admin side. Not much we can do about that part. As for the scrolling issue, be sure that you don't have the Fixed Position box under Display Settings checked. That will keep the popup fixed to the screen and it will stay there as you scroll. Otherwise it will scroll with the scroll bar.

**Comment by au85** [comment]
Thanks!

**Comment by au85** [comment]
One question please. I am using a menu button to activate the popup, is it possible to have the popup show next to the menu item instead of a new page? (I'm new to Wordpress, so please excuse my ignorance)

**Comment by danieliser** [comment]
Not sure what you mean by new page?

**Comment by au85** [comment]
Sorry, when the popup opens it appears to open on a blank page - behind the popup is just white, the entire menu disappears.

**Comment by danieliser** [comment]
@au85 that is the overlay, there is an option to disable it under Display Options.

**Comment by danieliser** [comment]
Or you can make it transparet by editing the Theme by navigating to Popup Maker -> Theme

**Comment by au85** [comment]
Thanks, I thought it would be simple!
