### ISSUE TITLE
1.7.30: `PUM_Extension_Activator` may have performance issues

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#610]
I was profiling my page load speeds today, and discovered Popup Maker is taking up a significant chunk of time (40% of total 1sec page load)

![image](https://user-images.githubusercontent.com/147228/48678348-c355e280-eb8a-11e8-8155-4d35419f83e3.png)

On our central staging, we have 600 plugins installed, which includes all custom development across all customers.

`get_plugin_data()` may be a surprisingly expensive deal here.

After doing a simple plugin toggle, page load speeds consistently went to 0.6 sec range as expected.

```
$ wp plugin toggle popup-maker popup-maker-remote-content
Plugin 'popup-maker' deactivated.
Plugin 'popup-maker-remote-content' deactivated.
Success: Toggled 2 of 2 plugins.
```

**Comment by danieliser** [comment]
@lkraav - Hmm, couple of things to note here before I propose a solution:

1. You have 600 plugins, far cry from even extreme "natural" edge case scenarios. Natural meaning someone who is running a site of their own, not managing lots of client sites in one install (not typical by any means on production).
2. We don't call get_plugin_data, core does, we call get_plugins so that we can check if PM is installed, activated or missing and notify properly.
3. Core caches these if you have caching enabled, so again this wouldn't normally be an issue on production. https://core.trac.wordpress.org/browser/tags/4.9.8/src//wp-admin/includes/plugin.php#L240

If you look at how core runs get_plugins I do see major room for improvement on both ends, though I think it may ultimately be unnecessary based on the 3 notes above, it is a simple fix and we love performance improvements of any kind, so here is what you can try now to confirm it works.

Change https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Extension/Activator.php#L99-L108

To 

		$popup_maker_data = get_plugin_data( WP_PLUGIN_DIR . '/popup-maker/popup-maker.php', false, false );

		if ( $popup_maker_data['Name'] == 'Popup Maker' ) {
			$this->core_installed = true;
			$this->core_path      = 'popup-maker/popup-maker.php';
		}

After looking at how they run get_plugins above I can change our code to go from checking all plugins and looking for Popup Maker, to just pulling for popup maker directly from get_plugin_data. That should alleviate the issue your seeing as it would bypass the mass loading of plugin data from your 600 plugins and only call it on the one we need.

Also per the docs for get_plugin_data it only pulls a few kb of the file to get the headers then stops
> https://core.trac.wordpress.org/browser/tags/4.9.8/src//wp-admin/includes/plugin.php#L36

Side note, you wanna see something really ugly, set a breakpoint here https://core.trac.wordpress.org/browser/tags/4.9.8/src//wp-admin/includes/plugin.php#L286

Then just run it over akismet & gravity forms. It literally loops through and loads the first 8kb of every php file in the main plugin folder. This is where your performance is lost, but not because of our plugin ;). Popup Maker and every extension only keeps one php file in the main plugin folder, and it showed in my testing there. Gravity Forms & Akismet had 5-8, each getting loaded partially to see if its the main plugin file. Worse yet, for Akismet it finds a match on the first file, still does the rest anyways.

Gonna submit a ticket on core track to see if that can't be improved upon vastly.

**Comment by danieliser** [comment]
Ok so after some discussion, appears we can't update core. There are situations (somehow) where users have plugins with multiple plugins inside one folder. WP detects each and YOU CAN activate them separately.

Just tested it with a simple extra file in the popup maker directory with plugin headers and a simple admin notice hooked in. Can be activated and deactivated separately from Popup Maker.

Eeek, what a scarry premise, but also means changing it likely won't happen, hopefully the fix I proposed on our end can do the trick for you.

**Comment by lkraav** [comment]
Thans a lot, I'll take a shot at it and get back to you.

**Comment by lkraav** [comment]
> 	$popup_maker_data = get_plugin_data( WP_PLUGIN_DIR . '/popup-maker/popup-maker.php', false, false );

Well yeah, I've always given the evil eye who do path-based checks... can't do `.git` directories etc.

But I guess it might be take it or leave it for time being.

**Comment by danieliser** [comment]
@ikraav - Oh we have 100+ plugins on wppopupmaker.com, but as you notice that is the typical range for a functional site, ~600 is well beyond what is considered normal use.

As for path based checks, that is identical to what core does, so it you don't see issues there you shouldn't with that change either.

Glad it worked.

**Comment by lkraav** [comment]
@danieliser is this change going to be part of PUM core?

**Comment by danieliser** [comment]
Already is in the latest dev branch ;), had to test it before I put the new solution up for you to try. Hate for a fatal error or something stupid.

**Comment by danieliser** [comment]
I just looked and neither have I pushed those commits yet nor did I properly tag this ticket in the commit message so it won't auto link. But its in the v1.8 feature branches.
