### ISSUE TITLE
Try to detect 403 load errors for asset caching and disable automatically.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#613]
Fix 403 errors with assets automatically.

**Comment by danieliser** [comment]
This rarely occurs, puniting to v1.10 so we hopefully have more details.

**Comment by fpcorso** [comment]
@danieliser For this one, should we have an admin notice appear if it detects 403? Should it check each time the cache file is generated?

Maybe check within the cache_file or up in the cache_css and cache_js methods. Right now, if cache_file returns false, the cache options are set to false so it just keeps retrying to generate the cache.

Here is the cache_file method: https://github.com/PopupMaker/Popup-Maker/blob/develop/classes/AssetCache.php#L331

Then, then returns up to cache_js, for example, which either sets the option to false or a time: https://github.com/PopupMaker/Popup-Maker/blob/develop/classes/AssetCache.php#L222 

Maybe, we flag within cache_file if any error occurs/403 is detected. And, instead of keep retrying on each pageload, maybe we set a wait/delay too.

**Comment by danieliser** [comment]
@fpcorso 

1. Yea I would think it should check each time it regenerates.
2. I'd say test inside the `regenerate_cache` method at the end, which is the only place `cache_js`, `cache__css` is called.
3. Yea I'd say another flag is in order. I wonder if we should add some underlying collector that handles multiple flags, alerts and such.

**Comment by fpcorso** [comment]
@danieliser The `regenerate_cache` method never gets used. Right now, when cache is refreshed, the options `pum-has-cached-css` and `pum-has-cached-js` are set to false. If false, then SiteAssets will individually call cache_js and cache_css.

The option is set to false in `reset_cache` which is called when our various settings are saved or extensions added or removed. Here is that method: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/AssetCache.php#L547

Here is where it is hooked into different actions: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/AssetCache.php#L62

Here is the call for cache_js: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Site/Assets.php#L198
Here is the call for cache_css: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Site/Assets.php#L337

**Comment by danieliser** [comment]
Hmm, I guess lets try it your way. It should probably also detect 403, 404, 500. I guess anything other than 2xx really.

**Comment by fpcorso** [comment]
@danieliser While building this out, I realized that the message we would display in a potential alert for this is very similar to the alert I created with the failing of generating the cache files. And, the learn more here would point to the same docs that walk them through testing, getting debug logs, and ways to fix. So, why not just use the same flag we have (`pum_files_writeable`) for this too? I did that for now so you can see what that looks like over in the pull request.

**Comment by danieliser** [comment]
Makes since, can always set a subflag later and tweak the messaging if needed.

**Comment by fpcorso** [comment]
@danieliser Awesome! Then this was finished yesterday. Let me do a few quick tests and then I'll make you as a reviewer on the pull request when it's ready for review/merging.
