### ISSUE TITLE
Check for and replace usage of esc_attr_e where needed.

### ISSUE THREAD

**Issue by danieliser** [PopupMaker/Popup-Maker#625]
esc_attr_e runs strings through translation via _e.

replace with echo esc_attr where needed.

In most cases this is fine, but in cases for things like option values which are used in JavaScript translating those strings can be bad. This was made apparent when Advanced Theme Builder used it to ouput the value for options. the value "image" got translated and prevent JavaScript from showing fields dependent on the "image" value.

**Comment by fpcorso** [comment]
Almost all the ones I see in the search (https://github.com/PopupMaker/Popup-Maker/search?q=esc_attr_e&unscoped_q=esc_attr_e) appear to be classes, slugs, element names, etc.. which all can be switched to the esc_attr as suggested. Do you see any in that last that should remain @danieliser?

I can work on this one today or tomorrow to get it closed out.

**Comment by danieliser** [comment]
@fpcorsoOnly place you wouldn’t wanna change it would be if the string needed translation but I don’t think you can pass text-domain.

**Comment by fpcorso** [comment]
@danieliser Okay, I'll start going through these. Most look like should be changed.

Sde note: Yes, we can do text domain in esc_attr_e
![image](https://user-images.githubusercontent.com/9730040/72459233-50e59000-3798-11ea-82a5-55e174266b0a.png)

**Comment by fpcorso** [comment]
@danieliser This one is finished. Forgot to add the "echo" to a couple and had to do a second commit to add them in.

Tested the changes on a test site and everything works as intended.

**Comment by danieliser** [comment]
@fpcorso Did you replace `echo esc_url` with `echo esc_attr` for a particular reason? Just reviewing commits and noticed it, making sure it was intentional.

**Comment by fpcorso** [comment]
@danieliser Yeah, since esc_url is used for displaying the URL, it encodes the &. Since we are pulling the url from a JSON list, which may or may not have query parameters, such as UTM parameters, I thought it would be better to use esc_attr there to prevent the links from not working right if we add in query args to any in the future.

Also, a few of the other anchor elements in the Extend page were already using esc_attr instead of esc_url so I also switched to make them all consistent.
