### ISSUE TITLE
Undefined property: WP_Post::$filter upon first save of a popup

### ISSUE THREAD

**Issue by rkaiser0324** [PopupMaker/Popup-Maker#632]
This is using v1.7.30 of the plugin, with error reporting at E_ALL.  Upon first save of a new popup the following PHP notice is thrown:

```
Notice: Undefined property: WP_Post::$filter in /media/sf_shared/project/web/wp-includes/class-wp-post.php on line 333
Call Stack
#	Time	Memory	Function	Location
1	0.2116	441856	{main}( )	.../post.php:0
2	17.3070	102197888	edit_post( )	.../post.php:206
3	17.3684	102193888	wp_update_post( )	.../post.php:399
4	17.3704	102226160	wp_insert_post( )	.../post.php:3821
5	17.8097	102376952	do_action( )	.../post.php:3748
6	17.8097	102377328	WP_Hook->do_action( )	.../plugin.php:453
7	17.8097	102377328	WP_Hook->apply_filters( )	.../class-wp-hook.php:310
8	17.8101	102377728	WC_Admin_Meta_Boxes->save_meta_boxes( )	.../class-wp-hook.php:288
9	17.8101	102377728	wp_is_post_revision( )	.../class-wc-admin-meta-boxes.php:192
10	17.8101	102377752	wp_get_post_revision( )	.../revision.php:251
11	17.8101	102377752	get_post( )	.../revision.php:330
12	17.8101	102377752	WP_Post->filter( )	.../post.php:650
13	17.8101	102378168	WP_Post->__get( )	.../class-wp-post.php:354

```

**Comment by danieliser** [comment]
@rkaiser0324 - Hmm, sorry to say I don't think the issue is on our end based on what you have so far.

1. We don't deal with post filter attribute anywhere in our code, nor do we process the core post object at all, only save meta during the process in question.
2. Nothing in the stack trace points to our code, but rather to WC_Admin_Meta_Boxes which appears to be maybe related to WooCommerce (WC)?
3. 1.7.30 has been out for quite a long time, since I develop with the same error reporting modes enabled and this has never come up, even with WC active next to our plugin.

Its gonna be a conflict with another plugin or theme, may or may not be WC related.

Leaving this open for a bit if you want to respond, but I would suggest trying the health check plugin to see if it happens when only Popup Maker is active, my guess it won't.

**Comment by danieliser** [comment]
@rkaiser0324 What happens if you activate WooCommerce, and deactivate Events Calendar. Its possible Events calendar is the source and the error only turns up inside WC when its active.

If the error doesn't exist when WC is active and EC is not then we have at least narrowed it down.

**Comment by rkaiser0324** [comment]
Turned out that all these two plugins were a red herring.  The plugin culprit was actually a different one: [SEO Redirection Premium](http://www.clogica.com/product/seo-redirection-premium-wordpress-plugin) v2.22.  Deactivating that gets rid of this error. 

Sorry to take your time.  I am closing this out.

**Comment by danieliser** [comment]
@rkaiser0324 awesome, glad you were able to track it down.
