### ISSUE TITLE
JS error: Uncaught TypeError: Cannot set property 'popups' of undefined

### ISSUE THREAD

**Issue by rkaiser0324** [PopupMaker/Popup-Maker#635]
Version tagged 1.7.30. Latest version of Chrome, 71.0.3578.98.

This is due to `late_localize_scripts()` - currently you have

```php
echo 'window.pum_vars.popups = window.pum_popups;';
```

Shouldn't it be
```php
echo 'window.pum_vars = {}; window.pum_vars.popups = window.pum_popups;';
```

Doesn't seem to affect popup display though.

**Comment by danieliser** [comment]
Never seen this before in support, so unlikely its caused by the code on our end. That said the short answer, no it wouldn't be.

If you read the if statement above that line it says, if the script hasn't already been rendered, localize it the normal way, if it has already been rendered assign a global variable (same as localizing), then clone that variable into the global pum_vars object.

Since the cloning into the object only occurs if the pum-site-scripts are already loaded, that variable already exists, if we made the change you suggest we would overwrite all the variables already declared.

IE this only runs if the window.pum_vars is already on the page in the first place.

The only reason you would get that error is if your assets were not loading the normal way, IE are you using an optimization plugin that is combining them or moving them from footer to head etc. If so its telling WP its loaded, but not rendering it until after our code there gets rendered.

In any case haven't seen any other reports of this in the forums or support, so were gonna have to treat it as a localized conflict which we can try to debug.

**Comment by rkaiser0324** [comment]
@danieliser you were absolutely correct - this was caused by a minification plugin, namely [BWP-Minify](http://betterwp.net/wordpress-plugins/bwp-minify/).  Bypassing it avoids this JS error.  Thanks for the explanation.

**Comment by danieliser** [comment]
Gonna add the change above just in case.
