### ISSUE TITLE
Ninja Forms Actions not registered.

### ISSUE THREAD

**Issue by kjohnson** [PopupMaker/Popup-Maker#697]
This seems to be a regression caused by 3d90fe5d8fe5eb82235ae2b3e3df011c50f8ee0e and released with PUM v1.8.12.

The NF_PUM class is constructed on `init`, which misses the `ninja_forms_register_actions` filter, which is hooked on `plugins_loaded`. See: https://github.com/PopupMaker/Popup-Maker/commit/3d90fe5d8fe5eb82235ae2b3e3df011c50f8ee0e#r35467156

**Comment by danieliser** [comment]
So the original report was an issue of WPML + PM + Ninja Forms where popups were rendered 3x.

The only way this is possible is that the query itself is modified and returning the same result more than once.

They found that disabling NInja Forms prevented it from happening, and we traced it back to the PM / NF integration.

It was further narrowed to the OpenPopup action which calls `pum_get_all_popups()`

https://github.com/PopupMaker/Popup-Maker/blob/master/includes/integrations/ninja-forms/Actions/OpenPopup.php#L82

Commenting that out resolved it. One possible solution may be to do a check that we are on the NF Form editor before calling that function, otherwise return an empty array. This would likely fix his issue and allow us to revert this change.

For the full ticket check slack.
