### ISSUE TITLE
Error In Cache When WordPress Has Trouble Within Filesystem

### ISSUE THREAD

**Issue by fpcorso** [PopupMaker/Popup-Maker#730]
A user reported an error notice:

> Warning:ftp_mkdir() expects parameter 1 to be resource, null given

A different user reported a very similar notice:

> PHP Warning: ssh2_sftp_mkdir() expects parameter 1 to be resource, null given in /var/www/mysite/wordpress/wp-admin/includes/class-wp-filesystem-ssh2.php on line 519

I did a search in our code and realized we do not have ftp_mkdir() or ssh2_sftp_mkdir() anywhere in the code. However, in classes/AssetCache.php, we have a function called writeable() which calls mkdir() on the WP filesystem. https://github.com/PopupMaker/Popup-Maker/blob/master/classes/AssetCache.php#L91

After a little digging, I found that filesystem will use one of several options. One such option, the class WP_Filesystem_FTPext, creates the mkdir() method this way. It is the only ftp_mkdir() in any of the filesystem classes.

So, my theory is, that there is an issue within their filesystem setup (perhaps a plugin or hosting provider switches the filesystem to the ftp ext). But, it is only noticeable when our plugin is installed because our plugin is the only one calling a filesystem function during an admin pageload.

Within the WP_Filesystem(); function we call, it does return false if an error occurs so, maybe we should capture the return value of our function call and only move on to the mkdir() method call if the value is true?
https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/file.php#L1762

Was digging a little into the Filesystem as I was writing the response for the user and realized that the api records errors during the process, such as when connecting fails so it may be possible to use that somewhere in logs, possibly. https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-filesystem-ftpext.php#L37.

**Comment by fpcorso** [comment]
@danieliser For this issue, should we just return false if the filesystem doesn't initialize or should we do anything more, such as throwing exception or logging errors?

**Comment by fpcorso** [comment]
Copied from Slack message:

> If anything set an option that says it works or doesn't, then:
A. Bypass checking next time while that option is false
B. If that option is false we could then add an admin notice with a dismiss & try again link that notifies them of the issue.

@danieliser Do you want to do this approach you had theorized earlier in Slack? Or, for now, we can just return false early if the filesystem doesn't initialize.

**Comment by fpcorso** [comment]
Not sure if we should build that much out considering we've only had 1 report in 400k sites. Maybe just the return false for now?

**Comment by danieliser** [comment]
@fpcorso The issue with just returning false is how will we know when that is occurring?

Otherwise add the false for now and create a new issue to improve later with notifications.

**Comment by fpcorso** [comment]
Copied in from Slack:

> I wonder if when we detect an error there and plan to return false, if we should:
> 1. set a flag in wp_options
> 2. while that flag is set filter pum_settings and disable asset caching.
> 3. while that flag is set show an admin notice describing we detected a problem and switched to a less performant solution.
> link to dismiss, keeping the fallback in place.
> link to undo and dismiss
> link to learn more
> 4. when they dismiss it unset the flag. (edited)

**Comment by danieliser** [comment]
@fpcorso What is left to finish on that list?

**Comment by fpcorso** [comment]
Looking through the code, I don't see where pum_settings affect caching @danieliser. Most places, such as https://github.com/PopupMaker/Popup-Maker/blob/4fb57dfee67a7b2dbe1bda14a7c0da18cebccbf6/classes/Site/Assets.php#L194, call ::enabled() which checks the constant PUM_ASSET_CACHE. So, I am unclear where to filter as you mentioned in point 2 of the list above.

**Comment by fpcorso** [comment]
@danieliser Do we have some admin notice system/class in place to add these into or should I add it into the AssetCache class?

**Comment by danieliser** [comment]
@fpcorso So for the flag method outlined above you would need to manually set the flag in wp_options likely would be better than pum_settings. Then we can clear it easily.

For performance reasons though we should probably set a flag that it works, then change it to false when there is an issue. If we don't set a value it will cause an extra query to check if it exists every time its used rather than being loaded with all_options.

But for #2 in the list, see [here](https://github.com/PopupMaker/Popup-Maker/blob/master/classes/AssetCache.php#L57)

Essentially you can filter the value returned by that function [here](https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Options.php#L80): 

Beyond that I'd probably:


1. Check for `get_option('pum_files_writeable', null) === null` and if true `add_option('pum_files_writeable', false);` Also call `pum_reset_assets()` to make AssetCache run again on next load to set the flag properly.
2. In asset cache file write test check the flag and update it if something has changed. IE if its set to true, and filewrite fails, set it to false.
3. When `get_option('pum_files_writeable', null) === false`, that is the `flag` I'm referencing, maybe add a helper function somewhere to check this as a boolean and set it if missing.
4. while that flag is set show an admin notice describing we detected a problem and switched to a less performant solution.
- [ ] link to dismiss, keeping the fallback in place.
- [ ] link to undo and dismiss
- [ ] link to learn more
5. when they dismiss it unset the flag.

**Comment by fpcorso** [comment]
@danieliser When they click to undo and dismiss, it will reload the page, removing the admin notice. But, if the issue still occurs, it will automatically add the notice back during the caching process which will result in them immediately seeing the admin notice again. Is that enough to make them see the issue is still there or should we have a different message after they clicked the button saying that it didn't failed again.

**Comment by fpcorso** [comment]
@danieliser Any thoughts on where to link to learn more? The causes are so varied that writing something up could be a massive amount of content that they may not understand. Or, should our notice have the call to action to be to contact their hosting provider?

**Comment by fpcorso** [comment]
@danieliser Current version of the notice. Any thoughts on wording?

Desktop:
![image](https://user-images.githubusercontent.com/9730040/72938558-2ddb5300-3d39-11ea-8295-2f2bb1e8e907.png)

Tablet:
![image](https://user-images.githubusercontent.com/9730040/72938580-3764bb00-3d39-11ea-9e10-9a38e98bfe3a.png)

Phone:
![image](https://user-images.githubusercontent.com/9730040/72938602-40ee2300-3d39-11ea-8355-532f8ee10588.png)

**Comment by danieliser** [comment]
@fpcorso 

1. I forgot to mention we do have an alert system already. It is a passive not active system though, so you add messages via a filter at runtime currently, rather than recording a message into the database that will be queued to view later. The review requests, translation requests, upgrade notices etc all use it. You will see it with our log and a wrapper around all the notices.

**Alerts:** ([source](https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Alerts.php), [example](https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Upgrades.php#L81))

2 When they click dismiss, I think it should either confirm they are aware that the issue exists and want to leave it in safe mode, in which case you remove the flag and simply permanantly update the global PM setting to disable_asset_cache. If they undo, maybe set the `pum_files_writeable` value to something other than true/false/null, possibly dismissed, or even a timestamp set to 2 weeks after its dismissed, so it can show up again.

3. Our doc on the matter may link of to varying info about general failure reasons for the filesystem as well as mention requesting host assistance to work out why it isn't working.

4. Besides moving it into an Alert framework, which should handle the dismissal tracking in #2 above as well instead of doing a timestamp as well as put the logo and such. I'd change the buttons to text links like our review requests in a bullet list and reword it slightly like so:

`Popup Maker detected an issue with your file system's ability and is unable to create & save cached assets for your popup styling and settings. This may lead to suboptimal performance. Please check your filesystem and contact your hosting provide to ensure Popup Maker can create and write to cache files.`

Other than that the styles you added may or may not be needed with the Alerts system, if mobile tweaks are needed, probably best to do them for all alerts in the scss files.

Will review & test everything tonight, but looks good so far.

**Comment by fpcorso** [comment]
@danieliser Updated to use alert system, new wording, and your preferred list:
![image](https://user-images.githubusercontent.com/9730040/73013069-9122bf00-3de5-11ea-9fe1-b3805bb1039b.png)

Not sure about switching to text links. Should we still at least use the button styling to for the try again link to draw more focus to that one?

Still have to redo the final part of what happens after clicking one of the options but almost finished.

**Comment by fpcorso** [comment]
@danieliser In addition to the question above, should we turn off the disable cache feature if they click try again?
![image](https://user-images.githubusercontent.com/9730040/73019115-f7f9a580-3df0-11ea-9d7a-32061ba01b68.png)
Since we turn it on, it would make sense to also turn it off but I could see a scenario where an admin had manually turned it on or wants it on between these notices. So, if they click try again, should we also turn off the disable?

**Comment by fpcorso** [comment]
Also @danieliser, in addition to the two questions above, I still don't quite see how the dismissing and expiration works in the alert system. I see there is a key of `expires` which is used in the AJAX handler: https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Alerts.php#L438

And that comes from the dismissable value but only when not exactly true in the JS file here:
https://github.com/PopupMaker/Popup-Maker/blob/master/assets/js/src/admin/general/plugins/alerts.js#L9

But, if the value evaluates to true, such as passing an expiration number, it adds the is-dismissable class and a "Dismiss this item" button here:
https://github.com/PopupMaker/Popup-Maker/blob/master/classes/Utils/Alerts.php#L350

Since we want them to take action, such as try again or keep the method, I am not sure we would want them to be able to dismiss without taking any action. Also, how do you set those two buttons to trigger the alert dismiss/expiration? Just by adding `pum-dismiss` classes to them or is there something else needed?

**Comment by fpcorso** [comment]
Everything works in the current 730 branch as intended except being able to have the alert come back after X time which I believe requires this expiration piece. Other than that, it is finished with the updates needed.

**Comment by danieliser** [comment]
@fpcorso 

1. Hmm I don't love 3 buttons, seems obnoxious, but we can try 1 to start with and make the others smaller text links. Did you look at the review alert options which are represented as pure text links in an unordered list? Was there a particular reason you think buttons are more appropriate?

Otherwise looks good in the alert box. PS stole that concept from Yoast to some degree.

2. So you want an expiration but not show the dismiss button? If so maybe overthinking it, on the surface we have a button (`Keep Current Method`) that is a dismiss already. Just associate the normal dismiss button with that same action. Alternatively we can add an extra arg to an alert for explicitly setting is-dismissible.

3. I believe adding pum-dismiss should be all that is needed, but check the review alert for confirmation on what it does for that link.

**Comment by fpcorso** [comment]
@danieliser Yeah, now that I look back at it after a little time away, I am not loving having all 3 buttons. However, for me, I feel buttons imply action whereas links imply going somewhere. So, I would say the learn more should definitely be a link. I looked at the review message while working on this. I am fine with either way. Just thought the buttons made sense if we wanted them to do an action.

I'll play with the dismiss a bit shortly.

Since I was hoping to get beta out earlier this week, I'll probably stay up a bit tonight to finish and test this to be ready for merging.

**Comment by danieliser** [comment]
Cool, let me know, will be around.

**Comment by fpcorso** [comment]
@danieliser As links:
![image](https://user-images.githubusercontent.com/9730040/73114743-6b7fdd80-3eeb-11ea-83a6-292d2204dbda.png)

**Comment by danieliser** [comment]
@fpcorso For the doc on this, we should mention this fix, has helped a couple people:

https://pantheon.io/docs/plugins-known-issues#define-fs_method
