### ISSUE TITLE
Re-unify with core notification design

### ISSUE THREAD

**Issue by lkraav** [PopupMaker/Popup-Maker#804]
![image](https://user-images.githubusercontent.com/147228/79983248-25b5bf80-84b0-11ea-954d-c9b1ea3995bd.png)

https://twitter.com/johnbillion/status/1249345662375931906 reminded me that... there's probably a way to have a core-style notifications with a designed branding element in there :thinking:

**Comment by danieliser** [comment]
@lkraav Happy to look into it, but:

a) we don't generally show alerts on all pages of the dash like the tweet you mentioned described. Only specific notices, deemed global, are shown on pages other than our own, that might include data migration notices for required actions.

b) we grouped our alerts (which required the custom box) because if there are several in a row, we don't want them strung all over the admin mixed with other plugin's notices that were not as well organized.

c) we took a little inspiration from Yoast in that we wanted to make it so some notices could be silenced / disabled, but still visible. This hasn't manifested in core yet, but may soon with some of our extensions for things like reminding people to finish setting up their MailChimp integration.

Personally I'm with you and have been fighting to make everything match core from the beginning. Notice all of our tabbed forms, modals, buttons & interfaces all stick close to core.

- Those are pretty much 100% core styles already 😉.
- The alerts themselves use core styles except for the close button.
- The box around it, the headings, shadows and colors are all pulled from core styles.

Otherwise to my knowledge there is no existing alert group element to pull styles from for this type of box. Essentially its a metabox with title, that contains alerts. Which is all pretty much spot on: https://wpadmin.bracketspace.com/

If you have some design concepts for us to look or specific suggested change I'd be happy to hear it, but they are pretty non-invasive already, attempting to adhere to best practices for where & when we show them, and use very little flare in terms of non-core-like styles.

Otherwise I'm not sure what this issue is suggesting at the moment based on the limited context and description given. Probably our fault as we have yet to set up issue templates 😜

**Comment by lkraav** [comment]
Thanks for the details. I'll play with CSS some and come back with an idea.

**Comment by danieliser** [comment]
@lkraav look forward to it.

**Comment by fpcorso** [comment]
I am going to go ahead and close this issue for now. @lkraav Feel free to come back to this if you get a chance to play with your CSS ideas.
