### ISSUE TITLE
Uncaught TypeError: t.addClass(...).position(...).trigger is not a function

### ISSUE THREAD

**Issue by pakklee** [PopupMaker/Popup-Maker#920]
## Describe the bug
JS error is causing popups not to open after WP 5.6/JQuery 3.5 update

## Site information
Popup Maker version: 1.13.1

WordPress version: 5.6

PHP version: 7.4

## Expected behavior
Auto-open, click triggered popups open as expected, etc

## Current behavior
Popups do not open

## Steps to reproduce
1. Visit wordpress 5.6 site with jQuery 3+
2. Pages with popup do not open due the JS error

## Errors
JS Console error - 
pum-site-scripts.js?defer&generated=1608235368&ver=1.13.1:7 Uncaught TypeError: t.addClass(...).position(...).trigger is not a function
    at s.fn.init.reposition (pum-site-scripts.js?defer&generated=1608235368&ver=1.13.1:7)
    at s.fn.init.p.fn.popmake (pum-site-scripts.js?defer&generated=1608235368&ver=1.13.1:7)
    at s.fn.init.open (pum-site-scripts.js?defer&generated=1608235368&ver=1.13.1:7)
    at s.fn.init.p.fn.popmake (pum-site-scripts.js?defer&generated=1608235368&ver=1.13.1:7)
    at pum-site-scripts.js?defer&generated=1608235368&ver=1.13.1:7

## Additional context
The specific error line -
t.addClass("custom-position").position(r).trigger("popmakeAfterReposition"),
in /assets/js/site.js:716

**popmakeAfterReposition** event doesn't exist, should be changed to **pumAfterReposition** - this seems to be an error from v1.3 when popmake was changed to pum?    After the trigger change I didn't have any further issues.

**Comment by danieliser** [comment]
@pakklee - So the error indicates something different than the conclusion you came too.

Specifically it is saying `.trigger is not a function`. But that function is part of jQuery which is a requirement for our plugin and WordPress in general at the moment.

This error has been around for a long time in our support queues. It most likely indicates an issue with your caching or optimization setup possibly not loading jQuery, loading multiple copies of jQuery, or loading it after our code is already running.

I will also point out we have thoroughly tested it with all of the planned jQuery migration. You can see there were similar reports in this topic here, but all have so far been found to be conflicts coming from 3rd party plugins.

As for `popmakeAfterReposition`, triggering a non-existent event just means nothing happens. Events are triggered for other code to listen for and run actions. If nothing is listening then no potential for errors. Further its still there because of backward compatibility, as in we trigger that event and there could be custom code still running on users sites that listened for that.

So we call old `deprecated` events like that so that user code doesn't break while we continue to make forward progress/changes.

Try these steps and see what you work out: https://wordpress.org/support/topic/wordpress-5-6-js-errors/page/2/#post-13773551

Happy to dig in further, but so far

**Comment by marcovieira17s** [comment]
Same error here with jQuery 3.5.1 if you try this $("body").addClass("custom-position").position(100).trigger("popmakeAfterReposition");
will result in same error... function trigger after function position is not allowed
