### ISSUE TITLE
Popup doesn't open if jQuery animation on the page

### ISSUE THREAD

**Issue by submediax** [PopupMaker/Popup-Maker#959]
Hi there,

If there is an active jQuery.animate then popup fails to open, e.g. 
`$( '.slider-indicator > span' ).animate( { width : "100%" }, autoplayTimeout );`

As far as I found, corresponding container #pum-XXX has wrong CSS properties `opacity: 0; display: none;` so it is not visible.

Please have a look. Thanks

**Comment by danieliser** [comment]
@submediax this has been reported several times, in all cases the issue isn’t something on our end, but usually some plugin or theme has either replaced the `.animate` function or the easing modes.

Just tested with some custom snippets now and didn’t see the issue, so I’d recommend using the Health Check plugins Troubleshooting mode to try and narrow down where the issue is coming from. My guess is the theme as that has been the case in all previous reports.

**Comment by submediax** [comment]
To tell the truth an issue we all observe caused by some update after June 2021.

Fortunately @mariatogonon [answer](https://wordpress.org/support/topic/popup-doesnt-open-if-jquery-animation-on-the-page/#post-14461835) on wordpress.org helped to overcome the problem so just using CSS does the trick `.pum-overlay.pum-active, 
.pum-overlay.pum-active 
.popmake.active {     
    opacity: 1 !important;     
    display: block !important 
}`

**Comment by danieliser** [comment]
@submediax - In late April 2020 WordPress released updates that moved toward jQuery v3 from the older v1.12 that was previously used. If your like ourselves we generally skip 5.x.0, and wait for 5.x.1 or 5.x.2 etc before installing then that would put you installing ~June.

Further in August they released yet another update in the progressive move towards new jQuery.

This is about the time that we saw dozens of people reporting all types of random JS craziness issues, all of which stemmed from their theme or another plugin having not prepared for those jQuery changes.

Since the original issue your reporting is also in that bucket of jQuery based issues, and nobody else is reporting similar issues, I'd think that further cements the idea this comes from somewhere else, and the fix Maria gave might mask the issue for you, but likely doesn't resolve the underlying problem.

So it may come up again in another way later.

Test it out with the Health Check plugin's Troubleshooting mode, works great for what its intended for.

**Comment by wassy83** [comment]
I have the same exact problem after updating to latest wp version with the divi theme,  the css fix is working but obviously I'm loosing the fade out in animation. Maybe someone know how to fix this with the divi theme...

**Comment by wassy83** [comment]
it wasn't the divi theme but a script that I have placed in homepage for a text that I want to blink: this is the code

`<script>
//Blink settings
var blink = {
    obj: $(".blink"),
    timeout: 9000,
    speed: 1000
};
//Start function
blink.fn = setInterval(function () {
    blink.obj.fadeToggle(blink.speed);
}, blink.speed + 1);
//End blink animation, after 'blink.timeout' millisecons
setTimeout(function () {
    clearInterval(blink.fn);
    blink.obj.fadeIn(blink.speed);
    blink = null;
}, blink.timeout);
</script>`

If I remove this code it works. So problem is here
